version: 2
models:
  - name: stg_events
    description: "Staging for synthetic web events"
    columns:
      - name: event_id
        tests: [not_null, unique]
      - name: user_id
        tests: [not_null]
      - name: session_id
        tests: [not_null]
      - name: event_name
        tests:
          - accepted_values:
              values: ['page_view','click','add_to_cart','checkout','purchase']
      - name: event_ts
        tests: [not_null]

  - name: fct_events
    description: "Core fact table of events"
    columns:
      - name: event_id
        tests: [not_null, unique]