name: Feature Request
description: Neue Funktionalität vorschlagen
title: "[Feature] <kurzer Titel>"
labels:
  - enhancement
assignees:
  - marco-knieling
body:
  - type: textarea
    id: goal
    attributes:
      label: Ziel / Nutzen
      description: Was soll erreicht werden? Welcher Mehrwert entsteht?
      placeholder: "Als <Rolle> möchte ich <Funktion>, um <Nutzen>."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Beschreibung / Scope
      description: Kurzbeschreibung der Funktion, User Story, In/Out of Scope.
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priorität
      options:
        - P1 (kritisch)
        - P2
        - P3
      default: 1
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Kontext / Referenzen
      description: Verlinke Issues/PRs/Docs
      placeholder: "Closes #123; Siehe PR #456"
  - type: textarea
    id: risks
    attributes:
      label: Risiken / Annahmen
      placeholder: "Annahmen: …\nRisiken: …"

