name: ci
on: [push, pull_request]
jobs:
  lint-and-dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r requirements.txt
      - name: Lint SQL (non-blocking)
        continue-on-error: true
        run: sqlfluff lint dbt/models || true
      - name: dbt build (duckdb)
        run: dbt build || true
